site_name: Django Admin Data Views
nav:
  - Home: index.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:  # https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md
    - python
    - json
    - console
