site_name: Django Admin Data Views
nav:
  - Home: index.md
  - Setup: setup.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:  # https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md
    - python
    - json
    - console

markdown_extensions:
  - pymdownx.superfences:

extra_css:
  - css/docs.css
