name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test.yml@v0.2.2
    with:
      env: '["py38", "py39", "py310", "py311"]'
