name: Test

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/test.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test-nox.yml@v0.6.2
    with:
      python-version: '["3.12", "3.13", "3.14", "3.15"]'
      exclude: '[{"os": "windows-latest", "python-version": "3.15"}]'
      allow-prereleases: true
      uv-cache-suffix: "test"
